### ISSUE TITLE
Reload files where resource path doesn't match web url path

### ISSUE THREAD

**Issue by pesterhazy** [adzerk-oss/boot-reload#102]
I've seen a few issues related to this but wanted to explain the problem again, with the hope of finding an elegant solution.

Consider this common scenario:

- clojure (ring?) serves `/public` from java resources. E.g. `/public/css/style.css` is served at `/css/style.css`. The idea is that all public assets are located in a single resource directory.
- you want to expose files to the public if, and only if, they're in `/public`
- your boot-cljs configuration is located at `public/js/app.cljs.edn`

In this scenario, boot-reload tries to load `/public/js/app.js`, but the files is actually (and properly) served as `/js/app.js`. If I understand the code, `:cljs-asset-path` doesn't work here because it will only prepend a string to the path, not change it.

Is my assumption correct that boot-reload doesn't cover this scenario? If so, what would be required to add support?

**Comment by Deraen** [comment]
Use `asset-path` instead of `cljs-asset-path`.

**Comment by darkleaf** [comment]
@pesterhazy see https://github.com/adzerk-oss/boot-reload/blob/master/src/adzerk/boot_reload/server.clj#L26-L28

`(reload :asset-path "/public")` work for me.

**Comment by pesterhazy** [comment]
`:asset-path` works for me, yes. Thanks!

I guess I was confused by the naming/docs, but then this was a dupe of https://github.com/adzerk-oss/boot-reload/issues/99
