### ISSUE TITLE
Reloading behaviour changes on migration to 2.7

### ISSUE THREAD

**Issue by IsaacKhor** [adzerk-oss/boot-reload#106]
On 2.6, reload uses the correct paths and finds the files correctly, but 2.7 somehow breaks this.

Looking at [this project](https://github.com/martinklepsch/electron-and-clojurescript/tree/fe8f65b04d2c8c2a45c17c8c548b1ebe9b6435cc) (link pinned at specific commit, let's hope that nobody rewrites history), if boot is upgraded to 2.7, reload starts to load files from `project-dir/main.out/stuff.js` instead of `project-dir/target/main.out/stuff.js`. Can be reproduced with other projects that I am running.

![image](https://cloud.githubusercontent.com/assets/6264789/21177352/bf2a2e2c-c225-11e6-833a-a8069230a10c.png)

Edit: add screenshot

**Comment by Deraen** [comment]
Boot-reload works fine in a "normal" project with Boot 2.7.0, so this seems to be related to something on Electron-and-ClojureScript project. Perhaps `target` task.

**Comment by Deraen** [comment]
@IsaacKhor Okay, Boot 2.7.0 removed deprecated `:target-path` env property which Boot-reload used until version 0.4.13. Fix this, update boot-reload and add `target-path` task option to `reload` task: https://github.com/martinklepsch/electron-and-clojurescript/compare/master...Deraen:patch-1

**Comment by IsaacKhor** [comment]
Ok, fix confirmed, going to close the issue.
