### ISSUE TITLE
0.5.0 todo

### ISSUE THREAD

**Issue by Deraen** [adzerk-oss/boot-reload#112]
- [ ] Where to read on-jsload option from in cljs.edn? Root or under `:boot-reload`?
- [ ] Support cases without cljs.edn file

**Comment by arichiardi** [comment]
About point #1, I was think of calling this kind of options `client-opts`, so `boot-reload` is fine. I am saying this because I can then just change the key name in order to produce to [this](https://github.com/bhauman/lein-figwheel/blob/master/README.md#client-side-configuration-options).

**Comment by Deraen** [comment]
Done.
