### ISSUE TITLE
Use of reserved Javascript keyword in adzerk.boot-reload

### ISSUE THREAD

**Issue by bago2k4** [adzerk-oss/boot-reload#113]
Hello,
here is a warning i get upgrading from 0.4.13 to 0.5.0 of adzerk/boot-reload:

```
Namespace adzerk.boot-reload.public.js.oc contains a reserved JavaScript keyword,
the corresponding Google Closure namespace will be munged to
adzerk.boot_reload.public$.js.oc at line 1adzerk/boot_reload/public/js/oc.cljs
```

Can I do something about this?
Thanks

**Comment by Deraen** [comment]
Hmm, currently not. The new version uses the cljs.edn path for the namespace name, and obviously in this case the path contains "public".

I think I need to add some reserved keyword mangling rules to the function that creates namespace name from the path.

**Comment by arichiardi** [comment]
I am curious to see if Boot-figreload handles this case 😀
