### ISSUE TITLE
Closure Library deleted goog.net.jsloader.loadMany

### ISSUE THREAD

**Issue by anmonteiro** [adzerk-oss/boot-reload#117]
As of https://github.com/google/closure-library/commit/6c5cf1e3563950d17b796295f57056e33e06c956 they deleted `loadMany`. When ClojureScript upgrades the Closure Library, `boot-reload` should move to `safeLoadMany` instead

**Comment by Deraen** [comment]
0.5.2-SNAPSHOT is available on Clojars, I'll release proper version when I have tested this in a few projects.
