### ISSUE TITLE
reload and multiple builds

### ISSUE THREAD

**Issue by piranha** [adzerk-oss/boot-reload#12]
I have two cljs files being built at same time - one for client part of application, and another for server part. And application just doesn't start when boot-reload is used, failing on call to `window`:

```
adzerk.boot_reload.reload.page_uri = (new goog.Uri(window.location.href));
                                                   ^
ReferenceError: window is not defined
```

Some mechanism of skipping some builds is desirable. :)

**Comment by piranha** [comment]
If we can decide on strategy here, I can write implementation myself.

One idea was to have some tag in entry point configuration map, like `:adzerk.boot-reload/skip true` or something like that.

**Comment by stephanos** [comment]
I'm in the same situation. Very interested in this.

**Comment by micha** [comment]
I think we should just disable adding the reload namespace to the `.cljs.edn` file when it contains `:compiler-options` with a `:target` key. An example `.cljs.edn` file for this case would be

```
{:require [foop]
 :init-fns [foop/init]
 :compiler-options {:target :nodejs}}
                    ^^^^^^^
```

**Comment by Deraen** [comment]
Check for `nodejs` is present and there is also now `ids` option to select to which cljs.edns to add boot-reload.
