### ISSUE TITLE
Reloads before boot-cljs has written resource

### ISSUE THREAD

**Issue by Jumblemuddle** [adzerk-oss/boot-reload#120]
Boot-reload has been trying to reload files before they've been written by boot-cljs and are ready to be served over http as resources by my server (aleph, using wrap-resource). I'd assume this wouldn't be an issue with a boot based http server. My .cljs.edn file is in a public folder in resources, so my server can serve the files.

My current workaround is to provide a delay for `boot-cljs` to save the file:

    (fn [next-handler]
      (fn [fileset]
        (let [fileset (next-handler fileset)]
          (Thread/sleep 100)
          fileset)))

That's far from ideal. Perhaps boot-reload could retry the file until it's ready? Afterall, if it's being told to reload a file, the file will definitely eventually be available.

**Comment by martinklepsch** [comment]
@Jumblemuddle can you provide your `build.boot` or the parts that you run during dev time?

**Comment by Jumblemuddle** [comment]
```
; user.clj
(ns user
  (:require
    [reloaded.repl :refer :all]
    [server.system :as system]))

(set-init! system/system)

; build.boot
(require
  '[adzerk.boot-cljs :refer [cljs]]
  '[adzerk.boot-reload :refer [reload]]
  '[com.stuartsierra.component :as component]
  '[environ.boot :refer [environ]]
  '[reloaded.repl :refer :all]
  '[server.system :as system]
  '[user])

(deftask dev []
  (comp
    (environ :env {:misc :misc})
    (repl :port 59258 :server true)
    (with-pass-thru _
      (go))
    (watch)
    (reload :asset-path "public" :disable-hud true :on-jsload 'client.core/render)
    (fn [next-handler]
      (fn [fileset]
        (let [fileset (next-handler fileset)]
          (Thread/sleep 100)
          fileset)))
    (cljs)))

; main.cljs.edn (in resources/public)
{:require          [client.core]
 :compiler-options {:optimizations :none
                    :asset-path    "main.out"}}
```

**Comment by Jumblemuddle** [comment]
It appears `boot-cljs` calls `boot.core/add-resource` before returning, so it should be present in the fileset when `boot-reload` tells the browser to reload the file. My only thought is that `clojure.java.io/resource` (which `ring.middleware.resource/wrap-resource uses) takes a little bit to refresh the temp dir created by boot.

**Comment by martinklepsch** [comment]
@Jumblemuddle hm. I would have been less surprised by this if you were using the `target` task but it seems you serve assets via the classpath [as recommended in the wiki](https://github.com/boot-clj/boot-cljs/wiki/Serving-files). 

1. What errors are you getting specifically?
2. Can you share how you set up your ring handler?

**Comment by Jumblemuddle** [comment]
I'm in the process of moving over to a static server as well using `boot-http`, which I think will solve the issue.
Just the intermitent failure to reload. (Due to a 404 to a js file)
It's really just an aleph server with `(wrap-resource "public")`

**Comment by martinklepsch** [comment]
@Jumblemuddle I really think whether you use `boot-http` or not should be irrelevant but won't hurt to try I guess :)

**Comment by Jumblemuddle** [comment]
@martinklepsch Yeah, still running into the same issue. Perhaps my cljs build is just too slow?

**Comment by Jumblemuddle** [comment]
![boot-reload](https://user-images.githubusercontent.com/3629343/30171338-57ef9ad0-93b7-11e7-8570-5211f43d3f2b.png)

**Comment by Jumblemuddle** [comment]
Also, it appears my boot-cljs task is running twice on each change... Is that normal?

**Comment by martinklepsch** [comment]
@Jumblemuddle the reload task should wait until the `cljs` task is done and by the time the cljs task is done all files should be persisted to disk accordingly.

Can you try inspecting the file after the `cljs` task has completed with a task like this:
```clojure
(with-pass-thru _
  (println (slurp (clojure.java.io/resource "main.out/client/core.js"))))
```

**Comment by martinklepsch** [comment]
> Also, it appears my boot-cljs task is running twice on each change... Is that normal?

One reason this happens could be that your cljs compilation writes files to `source-paths` or `resource-paths` which boot is watching, thus triggering a new build. Also think of macros that might do this kind of thing.

**Comment by Jumblemuddle** [comment]
The `with-pass-thru` should be after the `cljs` task, right? It find the file every time (twice), no matter how fast I'm changing files.

**Comment by Jumblemuddle** [comment]
I guess the double build is due to my use of macros from cljc files in cljs files.

**Comment by martinklepsch** [comment]
@Jumblemuddle do these macros write any files to the directories you specified in `source-paths` or `resource-paths`? 

My current guess is that something isn't right with your handler. When you tried with `boot-http` did you use the handler code that you used with Aleph as well? Maybe try using one of it's defaults. Also consider posting the handler code here.

**Comment by Jumblemuddle** [comment]
No, nothing is writing any files into my source directories or resources directories. (Asside from cljs into the tempdir version of my resources)
I was using the defauls `boot-http`

(deftask dev []
  (.start (Server/createTcpServer (into-array String [])))
  (comp
    (repl :port 59258 :server true)
    (with-pass-thru _
      (go))
    (serve :dir "resources/public")
    (watch)
    (reload :asset-host "http://localhost:3000" :disable-hud true :on-jsload 'client.core/render)
    (with-pass-thru _
      (println (slurp (clojure.java.io/resource "main.out/client/core.js"))))
    (cljs :compiler-options {:asset-path "http://localhost:3000/main.out"})))

**Comment by Jumblemuddle** [comment]
All of my resources are now pointing to `http://localhost:3000` for resources. `boot-cljs` creates the files and they're served, but not fast enough apparently.

**Comment by martinklepsch** [comment]
Can you paste the code for your handler please?

**Comment by Jumblemuddle** [comment]
What handler?

**Comment by Jumblemuddle** [comment]
There is no handler; just the default `boot-http`.

**Comment by martinklepsch** [comment]
The one that you used with Aleph before.

**Comment by martinklepsch** [comment]
With the usage of boot-http as you showed the 404 errors are correct because you serve files from `resources/public` and not from the classpath where the `cljs` task actually writes them.

```clojure
(serve :dir "resources/public")
```

**Comment by Jumblemuddle** [comment]
It does serve classpath resources properly as well though. It works about 50% of the time. (For all js files; main.js, main.out/client/core.js, etc.)

```
    (let [middleware (-> (bidi.ring/make-handler routes (partial handler database))
                         (wrap-resource "public"))
          server (aleph.http/start-server middleware {:port port})]
```

**Comment by Deraen** [comment]
Do other projects work for you? E.g. https://github.com/Deraen/saapas

**Comment by Jumblemuddle** [comment]
I belive the issue was being caused by Intellij's 'safe write' mode, which caused the double cljs build. Turning that off fixed the problem.
Perhaps it makes sense for `boot-reload` to retry a file for situations like this. :man_shrugging:.
Thanks for all your help, @martinklepsch, and for the suggestion @Deraen!

**Comment by Jumblemuddle** [comment]
It could still occur if someone was making rapid changes (perhaps editor auto save) and their cljs builds were particularly slow.

**Comment by Deraen** [comment]
Ah, I'm quite sure the problem is caused when boot-reload loads the file after next build cycle is started. At that point fileset and classpath don't contain cljs output.

For this reason serving files from classpath in dev is a bad choice and I've replaced this pattern in most of my projects. I should just get around to fixing the docs sometime...

**Comment by Deraen** [comment]
You can reproduce this is you have slow build and reload browser manually during the build.
