### ISSUE TITLE
Warn when using with advanced optimisations

### ISSUE THREAD

**Issue by martinklepsch** [adzerk-oss/boot-reload#15]
I think this bit: 

```
;; Thanks, lein-figwheel & lively!
(defn patch-goog-base! []
  (set! (.-provide js/goog) (.-exportPath_ js/goog))
  (set! (.-CLOSURE_IMPORT_SCRIPT (.-global js/goog)) (fn [file]
                                                       (when (.inHtmlDocument_ js/goog)
                                                         (jsloader/load file)))))
```

breaks with `:advanced` and really it probably shouldn't be supported anyways.

`patch-goog-base!` also [changed in fighwheel a bit](https://github.com/bhauman/lein-figwheel/blob/cec1b817b7234f9d92bf292f9b70d7db12420464/support/src/figwheel/client/file_reloading.cljs#L44) — maybe it's worth updating it in `boot-reload`?

**Comment by Deraen** [comment]
`patch-goog-base!` was changed in Figwheel when Nodejs support was added there, could be related to that.

Adding check for `advacned` would be good idea, but it's no use to check .cljs.edn as it can be set also as task option. Boot-cljs could start writing its task options to .cljs.edns.

**Comment by Deraen** [comment]
This will be easy to implement if/when we decide to merge this to boot-cljs task.
