### ISSUE TITLE
Make clearer the relationship with serve

### ISSUE THREAD

**Issue by benzen** [adzerk-oss/boot-reload#17]
I've managed to get this running of a quick projet.
Really cool stuff.

But i had to use the the serve task.
At first i've tried to use npm's http-server.

I'm pretty ok with this. But it will be much more nice is this relationship could be explicit.
At least on the readme.

Keep on the good work

**Comment by myguidingstar** [comment]
boot-reload just follows Boot's convention of composable tasks. I'm afraid you can't avoid reading about Boot itself
https://github.com/boot-clj/boot/wiki/Tasks
