### ISSUE TITLE
Specify reload path for browser

### ISSUE THREAD

**Issue by borkdude** [adzerk-oss/boot-reload#18]
Disclaimer: first weekend trying to use boot, so forgive me if I'm asking an ignorant question.

I am using this boot project:

https://github.com/borkdude/lein2boot/

I have an http server (serve task) serving the files from the target directory.
My handler (animals.api/handler) serves files under the "public" directory.
When I change a clojurescript file, the browser tries to reload the file using "/public/\<filename\>" but then I get a 404. How do I get it to reload from "/\<filename\>" instead?

**Comment by Deraen** [comment]
Instead of serving e.g. /css from public/css, serve /css from css.

This has been talked about a lot and the idea is that (in html) you should refer to the files using URL relative to your fileset, else we'll be in the same mess as Leiningen (you would manually set paths for each task).

**Comment by borkdude** [comment]
@Deraen I changed my setup and now reload works: https://github.com/borkdude/lein2boot/blob/master/build.boot

Now I have a different problem. My handler is serving all of my resources.
Is there any way I can have my public html/js/css in like "resources/public/js/foo.js" and have boot reload signal the browser to reload a file "/js/foo.js" and not "/public/js/foo.js"? I don't want to serve my whole resources folder...

**Comment by Deraen** [comment]
We discussed about this in IRC and we came to agreement that boot-reload level `:asset-path` option would be suitable solution.

https://botbot.me/freenode/hoplon/2015-06-01/?msg=40678747&page=1

**Comment by borkdude** [comment]
@Deraen sounds good

**Comment by m9dfukc** [comment]
Looks like my question at the [hoplon discourse board](http://hoplon.discoursehosting.net/t/boot-reload-cordova-how-to-get-reload-working/508) seems kind related?!

**Comment by Deraen** [comment]
This is a bit more tricky than I initially thought. E.g. with cljs asset-path works so that it's prepended to any generated paths. Instead we have to remove the path from relative path generated by Boot.

**Comment by borkdude** [comment]
Thanks!
