### ISSUE TITLE
Clojure .cljc files don't seem to be reloaded with boot-reload.

### ISSUE THREAD

**Issue by estsauver** [adzerk-oss/boot-reload#20]
I have a piece of cljc shared between frontend and backend. This piece doesn't seem to be recompiled/reloaded. 

Any suggestions on how to patch this in?

**Comment by Deraen** [comment]
Boot-reload shouldn't care about about cljc or cljs files, only js files.

Are you sure boot-cljs is recompiling the files?

**Comment by estsauver** [comment]
Your right, it was some transient issue where a build wasn't being cleaned. Nevermind!
