### ISSUE TITLE
Deprecations

### ISSUE THREAD

**Issue by kgxsz** [adzerk-oss/boot-reload#21]
Hi,

When I use this task I'm getting:

temp-dir! was deprecated, please use tmp-dir! instead
tmppath was deprecated, please use tmp-path instead

Is this related to which version of boot i'm using?

Thank you!

**Comment by martinklepsch** [comment]
@kgxsz Good catch. This has been fixed on master but not yet released.
@myguidingstar any chance we can cut a release at this point?

**Comment by Deraen** [comment]
Released.

**Comment by kgxsz** [comment]
Thank you!
