### ISSUE TITLE
Reloading of CSS fails with asset-path options

### ISSUE THREAD

**Issue by mitchelkuijpers** [adzerk-oss/boot-reload#23]
My css files did not seem to reload so I did some debugging with the following code:

```
(defn- changed-href? [href-or-uri changed]
  (when href-or-uri
    (let [uri  (goog.Uri. href-or-uri)
          path (.getPath (.resolve page-uri uri))]
      (.log js/console "path" path)
      (.log js/console "changed" (.getPath (.resolve page-uri (goog.Uri. (first changed)))))
      (.log js/console "ends-with?" (ends-with? path (first changed)))
      (.log js/console "ends-with-original" (ends-with? (first changed) path))

      (when (not-empty (filter #(ends-with? (.getPath (.resolve page-uri (goog.Uri. %))) path) changed))
        uri))))
```

When I try to reload a css file it always fails because path gets normalized so ```css/main.css``` will become ```/css/main.css``` and the changes file does not have this ```/``` before the path so ends-with? always fails. If you normalize it by doing .getPath this get's fixed. I could make a pull request but I am not sure this will break it for others.

**Comment by mitchelkuijpers** [comment]
Basically this fixed the issue for me: ```#(ends-with? (.getPath (.resolve page-uri (goog.Uri. %)))``` If my ramblings are bit confusing..

**Comment by martinklepsch** [comment]
Explanation makes sense, haven't tested it though. Let's just release as SNAPSHOT maybe?

**Comment by Deraen** [comment]
I pushed a snapshot. Please test.

**Comment by pandeiro** [comment]
There's a floating reference to `uri` on line 24 after the changes in 756aa2a

**Comment by martinklepsch** [comment]
I renamed it to `path` in 12f9ce1

**Comment by martinklepsch** [comment]
I wonder if anyone tested that build so far? It seems that `uri` should always have been `null` and at least cause a compiler warning? @mitchelkuijpers?

**Comment by pandeiro** [comment]
@martinklepsch Yeah it was causing a compiler warning; that's how I caught it.

**Comment by martinklepsch** [comment]
@pandeiro :+1:

**Comment by mitchelkuijpers** [comment]
@pandeiro @martinklepsch Whoops it looks like I screwed up, Sorry guys.

**Comment by mitchelkuijpers** [comment]
I see what i did wrong I extracted normalize-href-or-uri and then forgot the change the uri ref to path. Path should be a goog.Uri instance I created a pull request that fixes this: https://github.com/adzerk-oss/boot-reload/pull/27
