### ISSUE TITLE
Only send messages when socket is open

### ISSUE THREAD

**Issue by pandeiro** [adzerk-oss/boot-reload#25]
Currently `adzerk.boot-reload.websocket/transmit` fires `.send` unconditionally; checking that the socket is open with `adzerk.boot-reload.websocket/open?` first would only send messages when the socket is actually open.

The use-case for this is when boot-reload is loaded in browser environments (e.g. headless browsers) that may not have full websocket support, for instance in testing. Since boot-cljs doesn't currently support multiple `:optimizations :none` builds (and boot-reload would try to add itself to each `.cljs.edn` spec anyway, as currently written), this change would facilitate doing both development and testing with a single build even if it includes boot-reload.

**Comment by martinklepsch** [comment]
Closed by #26
