### ISSUE TITLE
Reloading ClojureScript doesn't work for non-root browser path if asset-path is set

### ISSUE THREAD

**Issue by alesguzik** [adzerk-oss/boot-reload#31]
Hi.

My setup is the following: css files and `application.cljs.edn` are stored in `/resources/public`, `:asset-path` for `cljs` task is set to `"/application.out"` , `:asset-path` for reload is set to `"public"`. The issue is that when I'm on non-root route of my application (e.g. `/users/1`), it tries to reload `application.out/.../file.js` (without leading slash), effectively reloading `/users/application.out/.../file.js`, which obviously does not exist on the server.

**Comment by Deraen** [comment]
PR merged.
