### ISSUE TITLE
adding new html includes without removing old ones

### ISSUE THREAD

**Issue by thos37** [adzerk-oss/boot-reload#47]
When I update a source file, new includes are being added to the html without removing old ones, which I think is causing the new code to fail to run correctly:

```
    <link href="/css/main.css" rel="stylesheet" type="text/css">
  <script type="text/javascript" charset="UTF-8" src="/js/app.out/ui/views/campaign_detail.js?zx=2mv0nsa82fsc"></script>
  <script type="text/javascript" charset="UTF-8" src="/js/app.out/ui/parse/routes.js?zx=152jvlqd1ell"></script>
  <script type="text/javascript" charset="UTF-8" src="/js/app.out/ui/main.js?zx=2yvaq9m9xlra"></script>
  <script type="text/javascript" charset="UTF-8" src="/js/app.out/ui/views/campaign_detail.js?zx=oq0sdtqyldgo"></script>
  <script type="text/javascript" charset="UTF-8" src="/js/app.out/ui/main.js?zx=8tiljqdeee8i"></script>
  <script type="text/javascript" charset="UTF-8" src="/js/app.out/ui/views/campaign_detail.js?zx=agdm71jxsatw"></script>
  <script type="text/javascript" charset="UTF-8" src="/js/app.out/ui/main.js?zx=kjlzljkgdu9j"></script>
  <script type="text/javascript" charset="UTF-8" src="/js/app.out/ui/views/campaign_detail.js?zx=76d2w5bv8jzx"></script>
  <script type="text/javascript" charset="UTF-8" src="/js/app.out/ui/main.js?zx=q9lylen9qckv"></script>
  </head>
```

**Comment by martinklepsch** [comment]
@thos37 If I understand correctly this would affect everyone and make things break for everyone? 

What version of `boot-reload` are you using? I haven't encountered an issue like this in my own usage before.

**Comment by Deraen** [comment]
Please describe the real problem, not presumed cause.

**Comment by thos37** [comment]
In my code I have a line like: 
```clojure
[:div.col-sm-4 [:div "hello world 3"]]
```

When I change the hello world string and save the file, new js entries are added to the html file, but the string itself does not change unless I reload the browser.  This is inside of an Om.Next component.  

What I'm hearing from you guys is that it's very unlikely to be a problem with boot-reload and is most likely some other aspect of my rendering process.  I'll attempt to duplicate the problem with a simpler test case.

**Comment by Deraen** [comment]
@thos37 So probably your code is split to separate files and you are not changing the file with `om/add-root!` call. Boot-reload doesn't currently work as well as Figwheel as it doesn't load the dependant namespaces when you change a file. You can use `on-jsload` option to make sure add-root is called.

https://github.com/adzerk-oss/boot-reload/issues/45

**Comment by thos37** [comment]
Thanks guys for taking a look at it and sorry for jumping to conclusions.  The stack of includes threw me.   I had my render function inside of a `(defn main)` which was only called on first load.  Calling render from `on-jsload` fixed it.
