### ISSUE TITLE
Reload from correct host

### ISSUE THREAD

**Issue by martinklepsch** [adzerk-oss/boot-reload#51]
I have a slightly strange setup where I serve compiled JS at `localhost:3333` and load it in an HTML file at `localhost:3000`. On first load everything is correctly loaded from e.g.:
```
http://localhost:3333/app.out/goog/dom/browserfeature.js
```
but when a reload event is triggered the reload code tries to reload from port 3000:
```
http://localhost:3000/app.out/com/gridacy/aura/app.js?zx=7r56fmv4tbeo
```
Screenshot in case it's not clear what I meant:
![screenshot 2015-12-17 14 40 11](https://cloud.githubusercontent.com/assets/97496/11870928/2dcce306-a4cc-11e5-8690-128cce121003.png)

I'll probably give this a go some time if someone already sees how this could be fixed, any pointers appreciated :)

**Comment by martinklepsch** [comment]
I guess there are two options:

1. Look at `document.currentScript` during first load and stash it into an atom (tradeoff: no IE)
2. Provide an option for the user to set it (tradeoff: manual configuration required)

I'm tending towards 1. other opinions welcome.

**Comment by Deraen** [comment]
I think manual option would be good enough and wouldn't require hacks, most users probably serve the files from same port as HTML.
