### ISSUE TITLE
Different websocket addresses for different simultaneous platforms

### ISSUE THREAD

**Issue by frankiesardo** [adzerk-oss/boot-reload#54]
We are running a cordova application that targets browser, ios and android.

The default reload address `ws:localhost:..` works wonder with the browser and the ios simulator, allowing us to push the changes to both simultaneously.

However the Android emulator remaps `localhost` to `10.0.2.2`. I can change my `build.boot` to use `(reload :ws-host "10.0.2.2")` , but this way we cannot develop with a single reloaded workflow on all three platform simultaneously.

Our ultimate dream is: having the three platform screens side by side and see our changes propagate to all of them in realtime :star: I wonder if boot has a way to accomplish this with.

**Comment by Deraen** [comment]
Not possible currently I think.

And I'm not sure what would be a solution to this. As far as I know the websocket client needs an address and port. Also, in client code it can be difficult to detect what is the current client.

One solution would be to the same hostname for websocket connection as is used to load the page, but that doesn't solve all cases so I don't think it's worth the complexity.

Maybe you could configure your network so that you have single IP which is accessible from all clients?

**Comment by Deraen** [comment]
To setup loopback alias for browser and maybe ios simulator:

```bash
# linux?
ifconfig lo: 10.0.0.2 netmask 255.0.0.0 up
# os x?
ifconfig lo0 alias 10.0.0.2

**Comment by frankiesardo** [comment]
Thanks @Deraen you comment made me realise that there is a very easy solution to this problem:

```clj
(task-options!
 reload {:ws-host (.getHostAddress (java.net.Inet4Address/getLocalHost))})
```

And voilà, the websockets connects to all three platforms without problems!

![screen shot 2016-01-08 at 10 04 05](https://cloud.githubusercontent.com/assets/1476561/12195531/c03db150-b5ef-11e5-9f23-e2982fb84288.png)

However, this story still has no happy ending. When I try to reload on android `boot-reload` does a call to GET `file:///Users/frankie/Projects/my-app/www/js/app.out/web/core.js?zx=vs40u6q9r42l` (my main namespace) but I think this fails for the same localhost problem. My guess is it should be `file://MY_HOST_IP/Users/frankie/Projects/my-app/www/js/app.out/web/core.js?zx=vs40u6q9r42l`. Do you guys know how can I tweak that behaviour (or monkeypatch it?)

**Comment by Deraen** [comment]
File urls never work with ips, they are always to local filesystem. Reload client is set to load files from same url as they were initially loaded.

This part of code is where JS files are reloaded: https://github.com/adzerk-oss/boot-reload/blob/master/src/adzerk/boot_reload/reload.cljs#L42-L44

**Comment by frankiesardo** [comment]
Interesting. Figwheel does not have the same problem because it uses a static file server to serve those files over `http://` rather than `file://`. Since `boot-reload` is already starting a server for the [websocket connection](https://github.com/adzerk-oss/boot-reload/blob/19b45624a9dd4db2927e35970c512529d19aa545/src/adzerk/boot_reload.clj#L26) it shouldn't be a massive change to serve the files from there?

I don't know if that's the direction `boot-reload` wants to go to, but if you think it's a useful addition I'm happy to help implementing this feature.

**Comment by Deraen** [comment]
Usually one uses boot-http or project http server to serve the files.

**Comment by frankiesardo** [comment]
Yeah but having it integrated in this plugin means `boot-reload` can call `reload-js` with a uri like `http://host:port/js/out/app.js` instead of `file:///Documents/...js/out/app.js`, thus allowing a user to pass a different host and port for emulators, or using something like ngrok with physical devices

**Comment by Deraen** [comment]
No, it shouldn't need to be integrated into this plugin. Boot-reload should already reload files over http BUT you probably need to load the HTML over http.

**Comment by frankiesardo** [comment]
> BUT you probably need to load the HTML over http.

That's the point. When running on a device (cordova, React Native) the file is not loaded over http. Wouldn't it be nice to support those platforms too?

**Comment by Deraen** [comment]
Boot-react-native seems to have some workarounds to make boot-reload work.

It would be nice to support those platforms too but I don't think integrating http server is needed for that. We could either require user to use boot-http or depend on boot-http and compose reload with boot-http to start server, but I would probably prefer the first option if the configuration doesn't get too complex.

Some kind of reload-url-fn or prefix option might be enough.

Do you have some example project I could take a look at?

**Comment by frankiesardo** [comment]
Yes, I have a very sample example pushed at https://github.com/frankiesardo/cadabra.

You can run only the Android platform if you like, that's the one I'm having problems with.

**Comment by martinklepsch** [comment]
maybe the `asset-host` option proposed in #52 would help with this as it allows to specify an alternative "root host" to load to-be-reloaded files from instead of deriving it from the intially loaded file?

**Comment by frankiesardo** [comment]
Yes, it works beautifully! Thanks a bunch for the help guys, I've updated the `cadabra` project to reflect this change if anyone wants to try it out.

This change is so good that it makes it trivial to use `ngrok` and make boot-reload work on real devices remotely. Exciting times ahead.

**Comment by martinklepsch** [comment]
Great to hear @frankiesardo! Took me a while to realize that the solution was already there haha.

Cheers! :beers:

**Comment by Deraen** [comment]
I'll be doing release this weekend.

**Comment by Deraen** [comment]
0.4.3 is now available.
