### ISSUE TITLE
Check for existence of DOM before using it

### ISSUE THREAD

**Issue by martinklepsch** [adzerk-oss/boot-reload#56]
When rendering he HUD and reloading CSS the ClojureScript code uses the DOM. While most projects certainly run in a browser context there is also React Native now which **does not have a DOM**.

To avoid runtime errors when using React Native any usage of the DOM should be done after checking if a DOM is available. Probably just `(exists?
 js/document)` would be enough.

**Comment by jellea** [comment]
A common practice seems to be to check for require being available in the js runtime. So `(exists js/document)`

**Comment by Deraen** [comment]
Is this fixed by #58 ?

**Comment by martinklepsch** [comment]
Yes
