### ISSUE TITLE
shared webworkers incompatible with boot reload

### ISSUE THREAD

**Issue by laforge49** [adzerk-oss/boot-reload#57]
Converted https://github.com/MarcoPolo/servant-demo from lein to boot here: https://github.com/aatree/aademos/tree/master/servant-demo

Everything works when you use lein, but when you use boot you get an error:

Uncaught ReferenceError: window is not defined
clojure.string.includes_QMARK_=function(a,b){return goog.string.contains(a,b)};adzerk.boot_reload.reload={};adzerk.boot_reload.reload.page_uri=new goog.Uri(window.location.href);adzerk.boot_reload.reload.ends_with_QMARK_=function(a,b){return cljs.core._EQ_.call(null,b,cljs.core.subs.call(null,a,cljs.core.count.call(null,a)-cljs.core.count.call(null,b)))};adzerk.boot_reload.reload.reload_page_BANG_=function(){return window.location.reload()};adzerk.boot_reload.reload.normalize_href_or_uri=function(a){a=new goog.Uri(a);return adzerk.boot_reload.reload.page_uri.resolve(a).getPath()};

The issue is that the same .js file is used for both the web page and the webworkers, which is what shared webworkers do.

The workaround is to comment reload out in boot.build.

**Comment by laforge49** [comment]
A fix would likely be to check to see if window is defined, as it is not in webworkers.

**Comment by martinklepsch** [comment]
Thanks that's a good catch. Do you know if reloading is technically possible within web Workers?
A similar issue (related to iOS) has been tracked in #56.

**Comment by laforge49** [comment]
Couldn't say, but I suspect not. But then I'm really surprised that reloading is possible at all.

**Comment by laforge49** [comment]
Oh, one thought. (But first realize that I am not a js dev!)

I was reading that in a webworker you should use self instead of the window object.

**Comment by laforge49** [comment]
Found it. In https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API/Using_web_workers#web-workers-api

Thus, using the window shortcut to get the current global scope (instead of self) within a Worker will return an error.

**Comment by laforge49** [comment]
Installed your updated code on my system and reran the boot-based servant-demo after reinstating reload in the dev task. Ran fine. Then I added a blank line to the end of the core.cljs file and saved the file. Crash. Unable to delete file.

So your fix may be good, but it raises another issue--not sure where.

See below:


C:\Users\Bill\Documents\aatree\aademos\servant-demo>boot dev
Starting reload server on ws://localhost:64938
Writing boot_reload.cljs...
Writing boot_cljs_repl.cljs...

Starting file watcher (CTRL-C to quit)...

nREPL server started on port 64939 on host 127.0.0.1 - nrepl://127.0.0.1:64939
Writing main.cljs.edn...
Compiling ClojureScript...
ò main.js
Starting Jetty on port 9000...
2016-01-30 20:42:12.196:INFO::clojure-agent-send-off-pool-0: Logging initialized @31951ms
2016-01-30 20:42:12.257:INFO:oejs.Server:clojure-agent-send-off-pool-0: jetty-9.3.1.v20150714
2016-01-30 20:42:12.366:INFO:oejw.StandardDescriptorProcessor:clojure-agent-send-off-pool-0: NO JSP Support for /, did not find org.eclipse.jetty.jsp.JettyJspServlet
2016-01-30 20:42:12.394:INFO:oejsh.ContextHandler:clojure-agent-send-off-pool-0: Started o.e.j.w.WebAppContext@53d65750{/,file:///C:/Users/Bill/.boot/cache/tmp/Users/Bill/Documents/aatree/aademos/servant-demo/ci0/s0070k/,AVAILABLE}
2016-01-30 20:42:12.412:INFO:oejs.ServerConnector:clojure-agent-send-off-pool-0: Started ServerConnector@302d4cd6{HTTP/1.1,[http/1.1]}{0.0.0.0:9000}
2016-01-30 20:42:12.419:INFO:oejs.Server:clojure-agent-send-off-pool-0: Started @32175ms
Elapsed time: 28.050 sec

java.io.IOException: Couldn't delete C:\Users\Bill\.boot\cache\tmp\Users\Bill\Documents\aatree\aademos\servant-demo\ci0\mm3x96\main.js
clojure.java.io/delete-file/invokeStatic        io.clj:  434
             clojure.java.io/delete-file        io.clj:  430
                                     ...                    
                   boot.file/delete-file      file.clj:   54
          boot.tmpdir.TmpFileSet/commit!    tmpdir.clj:  236
                       boot.core/commit!      core.clj:  383
    boot.task.built-in/fn/fn/fn/fn/fn/fn  built_in.clj:  264
       boot.task.built-in/fn/fn/fn/fn/fn  built_in.clj:  264
          boot.task.built-in/fn/fn/fn/fn  built_in.clj:  261
                     boot.core/run-tasks      core.clj:  794
                       boot.core/boot/fn      core.clj:  804
     clojure.core/binding-conveyor-fn/fn      core.clj: 1938
                                     ...                    
Writing main.cljs.edn...
Compiling ClojureScript...
ò main.js
java.nio.file.FileSystemException: C:\Users\Bill\.boot\cache\tmp\Users\Bill\Documents\aatree\aademos\servant-demo\ci0\mm3x96\main.js: The process cannot access the file because it is being used by another process.

      file: "C:\\Users\\Bill\\.boot\\cache\\tmp\\Users\\Bill\\Documents\\aatree\\aademos\\servant-demo\\ci0\\mm3x96\\main.js"
    reason: "The process cannot access the file because it is being used by another process.\r\n"
  sun.nio.fs.WindowsException.translateToIOException        
    sun.nio.fs.WindowsException.rethrowAsIOException        
    sun.nio.fs.WindowsException.rethrowAsIOException        
     sun.nio.fs.WindowsFileSystemProvider.implDelete        
sun.nio.fs.AbstractFileSystemProvider.deleteIfExists        
                                                 ...        
                                 boot.file/hard-link            file.clj:  145
                           boot.tmpdir.TmpFileSet/fn          tmpdir.clj:  251
                      boot.tmpdir.TmpFileSet/commit!          tmpdir.clj:  237
                                   boot.core/commit!            core.clj:  383
                   adzerk.boot-cljs/eval326/fn/fn/fn       boot_cljs.clj:  230
                   adzerk.boot-cljs/eval275/fn/fn/fn       boot_cljs.clj:  135
              adzerk.boot-cljs-repl/eval427/fn/fn/fn  boot_cljs_repl.clj:  171
                      boot.task.built-in/fn/fn/fn/fn        built_in.clj:  312
                      boot.task.built-in/fn/fn/fn/fn        built_in.clj:  310
              adzerk.boot-reload/eval514/fn/fn/fn/fn     boot_reload.clj:  125
                 adzerk.boot-reload/eval514/fn/fn/fn     boot_reload.clj:  124
                      boot.task.built-in/fn/fn/fn/fn        built_in.clj:  156
                boot.task.built-in/fn/fn/fn/fn/fn/fn        built_in.clj:  264
                   boot.task.built-in/fn/fn/fn/fn/fn        built_in.clj:  264
                      boot.task.built-in/fn/fn/fn/fn        built_in.clj:  261
                                 boot.core/run-tasks            core.clj:  794
                                   boot.core/boot/fn            core.clj:  804
                 clojure.core/binding-conveyor-fn/fn            core.clj: 1938
                                                 ...        
Elapsed time: 5.956 sec

**Comment by martinklepsch** [comment]
I think that's probably not caused by this fix but rather by https://github.com/boot-clj/boot/issues/397

As a workaround maybe you could try deleting your cache manually

**Comment by laforge49** [comment]
@martinklepsch I had come to the same conclusion. One bug was masking another, https://github.com/boot-clj/boot/issues/397

Unlike nx systems, windows does not delete read only files.
