### ISSUE TITLE
DOM does not update on changed Reagent components

### ISSUE THREAD

**Issue by Corkle** [adzerk-oss/boot-reload#59]
When modifying Reagent components, I have to manually refresh the page to see the changes to the DOM. I am currently forcing the DOM re-render in the REPL with `(reagent/force-update-all)` but I would love to have boot-reload take care of this.

I stumbled upon this conversation with the same issue, but I am not sure the solution of adding a reload hook: http://clojurians-log.mantike.pro/reagent/2016-01-22.html

**Comment by Deraen** [comment]
There is already a reload hook: `(reload :on-jsload 'frontend.main/init!)`

And you don't need to use `force-update-all` with reagent, just calling `render` again will work. Boot-reload will not try to handle specific libraries automatically.

**Comment by Corkle** [comment]
Of course! I see what I was missing now and it was right in front of me the whole time. Thanks for the quick response!
