### ISSUE TITLE
non-shared web-worker return references window

### ISSUE THREAD

**Issue by laforge49** [adzerk-oss/boot-reload#61]
A non-shared web worker does not have a window. But when such a web worker returns, a reference to window is made when using boot-reload. Specifically, window.location.protocol is referenced.

```
Uncaught ReferenceError: window is not defined(anonymous function) @ worker.js:2556
goog.events.EventTarget.fireListeners @ worker.js:2037
goog.events.EventTarget.dispatchEventInternal_ @ worker.js:2039
goog.events.EventTarget.dispatchEvent @ worker.js:2034goog.net.WebSocket.onOpen_ @ worker.js:2350
```

**Comment by martinklepsch** [comment]
This needs a reproduction case or in just more information. How did you conclude that `window.location.protocol` is accessed?

**Comment by Deraen** [comment]
Could be: https://github.com/adzerk-oss/boot-reload/blob/267c3dc94d6db36b2f603ff2a093eb6310ccbbb9/src/adzerk/boot_reload/client.cljs#L39

Maybe this was not problem with shared workers as they didn't try to open WS connection or something?

**Comment by laforge49** [comment]
Daraen,

Could also be for shared worker. My test for shared worker terminates the worker from the client.

Normally I would not run into this case, as workers normally wait for messages. I was just testing some new code and had disabled a bunch of code.

**Comment by laforge49** [comment]
Martin Klepsch,

https://github.com/aatree/aademos/tree/reload-tworker-failure/tworker is a branch in aademos where a minimal tworker fails.

How did I know the failure was in window.location.protocol? Because I opened the chrom console, and clicked on the source. This is what was highlighted.

**Comment by laforge49** [comment]
Daraen,

My error, this seems to have nothing to do with the exit of the webworker. Its just async as the code you referenced showed.

**Comment by Deraen** [comment]
I think the latest changes should fix this: Boot-reload no longer tries to access `window` when started. This doesn't however mean that boot-reload would work with Web-workers.

https://github.com/adzerk-oss/boot-reload/issues/109
