### ISSUE TITLE
Prepend :asset-path

### ISSUE THREAD

**Issue by nashbridges** [adzerk-oss/boot-reload#64]
We use clojurescript and boot with Rails as a backend.

The problem with default boot-reload setup is that Rails (Sprockets actually) serves its assets as "/assets/something.js". The prefix path itself could be changed, but it is required to avoid confilct with the other routes.

The following setup

```clojure
(deftask dev
  "Watch/compile clojurescript files in development"
  []
  (comp
   (watch)
   (speak)
   (reload :on-jsload 'hb.core/render-app)
   (cljs-repl)
   (cljs :compiler-options {:asset-path "/assets/main.out"})
   (target :dir #{"lib/assets/cljs"})))
```

write files to "lib/assets/cljs", which is treated by Sprockets as static root path. Therefore, main.js is accessible at "/assets/main.js".

The :asset-path option of cljs fixes paths in main.js itself, so we have correct `document.write('<script src="/assets/main.out/cljs_deps.js"></script>');` etc in it.

However, reload doesn't work, because it tries to load "/main.out/somewhere/something.js", while we need "/assets/main.out/somewhere/something.js".

Currently it could be hacked with :asset-host option as "localhost:8080/assets", however, this won't work reliably among all devs machines and CI.

Could we have :asset-path-fn, so it would be a dev responsibility to prepend or subtract prefix from current URL?

**Comment by esessoms** [comment]
I ran into this problem as well, working entirely in clojurescript.  No rails required.  I've written a patch to make the asset-path behavior more intuitive.

https://github.com/adzerk-oss/boot-reload/pull/65 or
https://github.com/esessoms/boot-reload/tree/output-dir

Try it out?

**Comment by jiyinyiyong** [comment]
Same here, it bothers.
![image](https://cloud.githubusercontent.com/assets/449224/13993121/f0e822cc-f159-11e5-8867-74896a83722c.png)

**Comment by Deraen** [comment]
#65 is now merged and deployed

**Comment by nashbridges** [comment]
@esessoms @Deraen Thank you!
