### ISSUE TITLE
on reloading a transpile-to-Clojure language

### ISSUE THREAD

**Issue by jiyinyiyong** [adzerk-oss/boot-reload#66]
Maybe this topic is beyond boot-reload but I want to ask about the possibility of making it to do so. It's common pattern in JavaScript that people write in another syntax and compile it to JavaScript. And I'm doing this on Clojure, and perhaps the only one currently. I mean I will compile my code in `.cirru` files into ClojureScript and then ClojureScript will be compiled to JavaScript.

Perviously I was using a lein plugin that compiling code from `cirru-src/` to `src/` and the file change event triggers another process called `lein figwheel...` I was lucky. Now I'm trying to use boot with boot-reload.

As I read code of boot-reload, I think it's getting all ClojureScript files and check `prev` fileset to find out changed files, and notify the browser. Now I want to add my boot task to compile `.cirru` file into `.cljs` before boot-reload is handling that. I want to ask if that's possible my boot talk to work correctly with boot-reload? Very tricky though. Thanks.

**Comment by martinklepsch** [comment]
@jiyinyiyong you can make a `cirru` task that compiles your files to `.cljs` and those will be picked up by the `cljs` task and later in the pipeline by the reload task. Definitely sounds doable. I suggest asking in the Slack channel if you're looking for further advice on how to implement this.

**Comment by laforge49** [comment]
Martin is right. All you need to do is write a task to do your compile.
When you compose your external task, the order of your sub-tasks will be
something like serve, watch, speak, reload, custom, cljs. (I'm assuming
boot-jetty here. For boot-http, I think serve goes at the end.)

**Comment by alandipert** [comment]
@jiyinyiyong compiling to ClojureScript is awesome!  Boot was originally motivated to make exactly this easy.  https://github.com/hoplon/boot-hoplon might be a useful reference.  It's the task for http://hoplon.io that compiles `.cljs.hl` into `.cljs` files and is compatible with all other boot-cljs tooling.

**Comment by jiyinyiyong** [comment]
@alandipert sounds good. Have you used that with boot-reload yet, does it work well?

**Comment by jiyinyiyong** [comment]
@martinklepsch I will ask in Slack next morning. Actually these lines of code made me worried. I tried to look into `fileset` emitted from watch, and it seemed to be a full list of files, and in boot-reload it compares all the files in order to find changes, which means I have to compile all my files. That is unlike incremental compiling:
https://github.com/adzerk-oss/boot-reload/blob/master/src/adzerk/boot_reload.clj#L18-L24
```clojure
(defn- changed [before after static-files]
  (when before
    (->> (fileset-diff before after :hash)
         output-files
         (sort-by :dependency-order)
         (map tmp-path)
         (remove static-files))))
```
I'll try to dig deeper...

**Comment by laforge49** [comment]
I believe this is the cost of easy composition. All the sub-steps are fully
decoupled. Efficiency in the form of incremental compilation goes out the
window. Your cljs converter shouldn't even need to know that it is being
invoked multiple times.

It is the KISS approach that can accomplish a great deal in a
straight-forward way. Without much in the way of preconceptions about what
needs to be done, which is what you often need but rarely get from a build
tool. And while it may seem inefficient, remember that the most valuable
resource is qualified developers and that such an approach lends itself to
use within a cluster. :D

Iron being really cheap these days.

**Comment by laforge49** [comment]
In my estimation, boot is pure genius. You just need to think cloud.

**Comment by jiyinyiyong** [comment]
@laforge49 I came from JavaScript community and Webpack already did a very good job on such cases. I mean files are compiled incrementally in develop mode. I believe there's a solution for Clojure too, but with the help of boot-reload supporting it.

**Comment by laforge49** [comment]
I find myself repeatedly in awe of the clojure community at large.

**Comment by martinklepsch** [comment]
@jiyinyiyong `boot-cljs` handles incremental compilation of cljs sources. And similarly you can implement your `cirru` compiler to do some sort of incremental compilation. `boot-reload` solely provides a mechanism to reload files in a browser, it has nothing to do with compilation, you can use it for CLJS and CSS and other types of files

**Comment by jiyinyiyong** [comment]
Thanks. I finished the plugin days back. Closing.

```cljs
(deftask dev []
  (set-env!
    :source-paths #{"cirru/src"})
  (comp
    (html-file :data {:build? false})
    (watch)
    (transform-cirru)
    (reload :on-jsload 'boot-workflow.core/on-jsload)
    (cljs)
    (target)))
```
https://github.com/mvc-works/boot-workflow/blob/master/build.boot#L82
