### ISSUE TITLE
Generic way to pass messages to HUD

### ISSUE THREAD

**Issue by martinklepsch** [adzerk-oss/boot-reload#72]
It would be cool if there would be a way for other tasks to send messages to the HUD.

e.g. a SASS task might encounter an error during compilation that could be shown to the user.

**Comment by arichiardi** [comment]
This maybe can open the doors to the cool error messages we see in figwheel ;)

**Comment by Deraen** [comment]
I'll probably work on this soon, I made less4clj ready for this last night and made progress with sass4clj.

**Comment by arichiardi** [comment]
Is there some (small) task you'd like me to have a look at? That's cool that you are checking this.
