### ISSUE TITLE
Feature request: wss support

### ISSUE THREAD

**Issue by jiyinyiyong** [adzerk-oss/boot-reload#75]
People may debug code in HTTP/2 since ClojureScript is always lots of small files, which is naturally fixed in HTTP/2. And since HTTP/2 is based on HTTPS, so `ws` is no longer working and we need `wss`. 

![image](https://cloud.githubusercontent.com/assets/449224/14918471/af95448e-0e56-11e6-9292-467a326a4310.png)

**Comment by Deraen** [comment]
Try `secure` option.

We could perhaps default to `wss` if the page is loaded using `https`. This can be determined by checking `location.protocol`.

**Comment by jiyinyiyong** [comment]
Tried just now and `:secure true` generates a `wss` as expected. There're still some issues. Since the WebSocket server created in Clojure does not come with a certificate itself, so I need an Nginx proxy to redirect the request. That means I cannot redirect a request to the port `45240` to a WebSocket server of `45240` because Nginx will find the port already used by Clojure. Do you have any solutions on this?

**Comment by jiyinyiyong** [comment]
Considering it's a problem of other tools. Closing.
