### ISSUE TITLE
Empty hostname makes the url invalid

### ISSUE THREAD

**Issue by ejlo** [adzerk-oss/boot-reload#77]
In electron, window.location.hostname seems to return an empty string instead of "localhost". It would be nice if resolve-url could default to "localhost" in this case, instead of returning an invalid url.

**Comment by shyblower** [comment]
Same problem with Firefox and Chromium.
You now have to explicitly configure ws-host to "localhost" though marked as optional in the usage docs.
It used to work in 0.4.5.

**Comment by Deraen** [comment]
Hmm, any more information on this?

I'm using Boot-reload fine without setting ws-host.

**Comment by Deraen** [comment]
I think this is same as https://github.com/adzerk-oss/boot-reload/issues/92
