### ISSUE TITLE
Asset-host with no / fails

### ISSUE THREAD

**Issue by arichiardi** [adzerk-oss/boot-reload#78]
Hello! I am using `boot-reload` with a custom setup that has an external server for the assets  therefore I specified `asset-host` to be my `http://localhost:8000`.

However, I get a big red error saying so:
```
reload.cljs?rel=1465762643152:51 Load failed: Jsloader error (code #0): Error while loading script http://localhost%3A8000/main.out/boot/cljs/main20000.js?zx=iq6caq3ogki8
```

Am I doing everything right?

<s>I see the colon is encoded so that might be a misuse on my part or a bug.</s>

Thank you Deraen as usual for you lib!

**Comment by arichiardi** [comment]
No ok the problem is elsewhere, basically I need to put a terminating `/` for it to work.
I will close the issue, but can I do something for making it more clear in the README?
Maybe add a normalization step that adds the `/` if not there already?

**Comment by Deraen** [comment]
Documentation improvements are always welcome :)

This information is not enough for me to guess where the problem is. When asset-path is used to modify reloaded file path,  it is appended "/" already: https://github.com/adzerk-oss/boot-reload/blob/master/src/adzerk/boot_reload/server.clj#L27

**Comment by arichiardi** [comment]
Oh ok, maybe there is some problem there then, I added `:asset-path `"http://localhost:8000/"` and it works file now...what else can I try?

**Comment by Deraen** [comment]
The way asset-path is implemented, that value is same as leaving it empty.

Asset-path works kind of reverse how it usually works in other tooling, the value is removed from the relative path being reloaded. E.g. when you change file public/js/foobar.js (relative to the fileset) and asset-path is set to "public" the public prefix of relative path is removed and "js/foobar.js" reloaded.

**Comment by arichiardi** [comment]
mmm...I don't know what is going on then, because when I add it, I see that `boot-reload` prepends that to all the files to reload, which is what I want...maybe a video of what I mean can solve the mistery...

**Comment by Deraen** [comment]
Huh, that's how `cljs-asset-path` should work (it is different from `asset-path`). Which one are you using? 

Or could be the code doesn't do what I think it should :D

**Comment by arichiardi** [comment]
no sorry, scratch scratch, I am in big confusion, I went to double check and I am using:
