### ISSUE TITLE
reload fails (on both safari and chrome with different errors)

### ISSUE THREAD

**Issue by paultopia** [adzerk-oss/boot-reload#82]
Here's something interesting.  I'm trying to get live reloading with the following build.boot: 

```
(set-env!
 :source-paths #{"src/cljs"}
 :resource-paths #{"html"}

 :dependencies '[[adzerk/boot-cljs "1.7.228-1"]
                 [pandeiro/boot-http "0.7.3"]
                 [adzerk/boot-reload "0.4.8"]
                 [org.clojure/clojurescript "1.9.76"]
                 [cljs-ajax "0.5.5"]
                 [reagent-utils "0.1.8"]
                 [reagent "0.6.0-rc"]
                 [reagent-forms "0.5.24"]])

(require '[adzerk.boot-cljs :refer [cljs]]
         '[pandeiro.boot-http :refer [serve]]
         '[adzerk.boot-reload :refer [reload]])

(deftask dev
  "Fake a Figwheel"
  []
  (comp 
   (serve :dir "target")
   (watch)
   (reload)
   (cljs)
   (target :dir #{"target"})))

```

However, live reloading fails.  In Safari (most recent version on OS X), I get 

>  WebSocket network error: The operation couldn’t be completed. Cannot allocate memory

followed by 

> Reload websocket connection closed. 

On Chrome, by contrast, I get this: 

> websocket.js:283 Uncaught SyntaxError: Failed to construct 'WebSocket': The URL 'ws://:62480' is invalid.

In either case, however, live reloading fails.

**Comment by Deraen** [comment]
Obviously the URL (`ws://:62480`) is invalid as it is missing hostname. What is strange is that 0.4.8 is working fine for me.

Also, not related to this, but I don't recommend using target task in development task. I wrote short piece about this at boot-cljs wiki: https://github.com/adzerk-oss/boot-cljs/wiki/Serving-files

**Comment by Deraen** [comment]
Problem is probably here: https://github.com/adzerk-oss/boot-reload/blob/master/src/adzerk/boot_reload/client.cljs#L24

Either `ws-host` is empty string (it should be nil), or js/window.location.hostname is empty. If you have time to check, it would be helpful if you can debug that function, console.log call should work fine:

```clj
(defn resolve-url [url ws-host]
  (let [passed-uri (Uri. url)
        protocol   (.getScheme passed-uri)
        host       (or ws-host (.-hostname (.-location js/window)))
        port       (.getPort passed-uri)]
    (js/console.log "ws-host" ws-host "hostname" (.-hostname (.-location js/window)))
    (str protocol "://" host ":" port)))
```

**Comment by paultopia** [comment]
Oh god.  It was my moronic mistake, and a total false alarm.  Very sorry!  I'm using a weird dev setup where I'm shoving compiled cljs files into an otherwise javascript-only chrome extension in a different project, and I just realized that I've been working with them from the file directly rather than from localhost.  Which is why window.location.hostname was indeed empty.  Very embarrassing... sorry for wasting your time.

**Comment by Deraen** [comment]
No problem :)

Also, when you are directly working with files, I think setting ws-host manually will work.

**Comment by Deraen** [comment]
And as this seems like case useful to guard against, I added a warning message which hopefully makes the problem clear: https://github.com/adzerk-oss/boot-reload/commit/4a4389058eaf82e3060e8db36055954d017a2a5f
