### ISSUE TITLE
How does dependencies tree affect reloading?

### ISSUE THREAD

**Issue by jiyinyiyong** [adzerk-oss/boot-reload#85]
For example, components dependend on each other like this:

```text
container -> sidebar -> group-line
```

As I edit `group-line`, what is supposed to happen?

I tried and put some results on Twitter https://twitter.com/jiyinyiyong/status/744196209259094016 Actually I got confused.

**Comment by martinklepsch** [comment]
@jiyinyiyong this is not enough information to give any useful comment unfortunately.

Generally all namespaces that have changed and namespaces depending on changed namespaces should get reloaded. If you can provide a minimal case that shows when this doesn't happen that would be most helpful. 

In theory one possibility could be that the hash for the file is exactly the same resulting in it not being regarded as different by `adzerk.boot-reload/changed` (pasted below) but I'm not sure if thats possible/likely.

```clojure
(defn- changed [before after only-by-re static-files]
  (letfn [(maybe-filter-by-re [files]
            (if only-by-re
              (by-re only-by-re files)
              files))]
    (when before
      (->> (fileset-diff before after :hash)
           output-files
           maybe-filter-by-re
           (sort-by :dependency-order)
           (map tmp-path)
           (remove static-files)))))
```

**Comment by jiyinyiyong** [comment]
I have [smaller](https://github.com/Memkits/smallist) example but no minimal case yet.

I'm always comspiling my code, is there a change it's influencing the dependencies?

**Comment by jiyinyiyong** [comment]
Figured out a solution on my side https://github.com/mvc-works/respo/commit/1f859dd7cdc7c55145fb8126fa0606a0ae1c56c3 . Closing for now since I don't have a good example.
