### ISSUE TITLE
goog.dom.constHtmlToNode is not a function

### ISSUE THREAD

**Issue by mattly** [adzerk-oss/boot-reload#87]
It looks like this function was added to Closure in [release 20160619](https://github.com/google/closure-library/releases/tag/v20160619), relatively recently. The changelog for 0.4.11 makes no mention of the fact that you'd need to update the Closure library, and I'm not certain how to do this outside of updating ClojureScript itself. You might want to make a note that the new version requires a newer Closure lib, CLJS version, or revert to the previous method of updating the HUD.

**Comment by skammer** [comment]
This is a nasty regression. Reverting to previous method of updating HUD would unfortunately break newer versions of ClojureScript, as Closure removed `goog.dom/htmlToDocumentFragment` as unexpectedly, as they added `goog.dom/constHtmlToNode`.

If checking whether `constHtmlToNode` exists and falling back to `htmlToDocumentFragment` in case it doesn't  is an acceptable solution, I'd be happy to provide a PR.

**Comment by martinklepsch** [comment]
@skammer I think a patch that makes things work with both versions of the Closure library would be very welcome, sorry about the breakage! :)

**Comment by Deraen** [comment]
Merged and included in `0.4.13`.
