### ISSUE TITLE
cljs build on cljs file change

### ISSUE THREAD

**Issue by karneaud** [adzerk-oss/boot-reload#90]
I'm new to the clojure thing so boot is quite a challenge in understanding. does boot-reload try to recompile the cljs files to js when the file changes?

**Comment by Deraen** [comment]
No.

Boot-cljs recompiles files when they change.

**Comment by laforge49** [comment]
Providing you've done a watch, of course.

**Comment by karneaud** [comment]
@Deraen  @laforge49 could it be the sequence then? [http://stackoverflow.com/questions/38537682/automating-with-boot-clojure/38538750#38538750](url)

**Comment by laforge49** [comment]
---------- Forwarded message ---------
From: CUSTOMERSERVICE ***@***.***>
Date: Mon, Mar 28, 2022 at 12:47 PM
Subject: Status of your SR819106682
To: ***@***.***>


Dear Customer,

Greetings from ICICI Bank.

we have completed your ICICI Bank request ReKYC Updation on 28-MAR-22.

Sincerely,
Customer Service Team.
ICICI Bank Limited.

This is an auto generated mail. Please do not reply to the same.
