### ISSUE TITLE
Reload websocket is related to assets?

### ISSUE THREAD

**Issue by jiyinyiyong** [adzerk-oss/boot-reload#95]
Found it strange that my reload websocket is missing after some changes. Tool me half an hour to track back my code and after reverting code like this I finally got it back:

``` diff
diff --git a/build.boot b/build.boot
index 9fc7510..7264f0c 100644
--- a/build.boot
+++ b/build.boot
@@ -59,7 +59,7 @@

 (deftask dev! []
   (set-env!
-    :asset-paths #{})
+    :asset-paths #{"assets/"})
   (comp
     (repl)
     (start-stack-editor!)
@@ -77,7 +77,7 @@

 (deftask build-advanced []
   (set-env!
-    :asset-paths #{})
+    :asset-paths #{"assets/"})
   (comp
     (transform-stack :filename "stack-sepal.ir")
     (cljs :optimizations :advanced
```

But why is "assets/" folder interfering WebSocket?

**Comment by Deraen** [comment]
Asset-path definitely shouldn't interfere with anything in boot-reload.

**Comment by jiyinyiyong** [comment]
This is the commit https://github.com/mvc-works/stack-workflow/commit/955a4304bcc8f19066b047ac0a07059343fa3932

I can reproduce it on OS X. Run `boot dev!` and see the console of `target/dev.html`.

**Comment by Deraen** [comment]
I'm trying to test this using that project, but there are other problems:

- As the project needs Clojure 1.8.0, you should add `boot.properties` file to project in case someone still is using Boot default of 1.7.0
- `repl` start at the start of `dev!` pipeline will block all other tasks when the repl client opens, you should probably start just repl server: `(repl :server true)`
- there is no `watch` task at the dev pipeline
- While not strictly necessary, I would suggest dropping `target` task from dev pipeline and serving files using http server directly from classpath, e.g. using https://github.com/pandeiro/boot-http, boot-reload will work better over http

**Comment by jiyinyiyong** [comment]
Thanks for the suggestions. I still need help in building tasks. My task is really tricky as I see.

> Clojure 1.8.0

Didn't know it works when file is put in project, will do it.

> repl

I want the task wait, I tried using `watch` before but got bugs. What do you mean by "block"? I see the followed tasks working fine.

> no `watch`

[boot-stack-server](https://github.com/Cirru/boot-stack-server/blob/master/compiled/src/stack_server/core.clj#L89) is a dirty task since it will call the `next-handler` many times, see `make-result` in the code. So watch is partly done by this task like "trigger it many times", what I need next it something to keep the task running. That's why this is a `(repl)` which looks like doing nothing.

Well, this task also brings up an web editor. That:s the dirty part.

> dropping `target`

I've been long serving code with Nginx,, which makes sure that I don't have to use another server on my VPS. And I don't have to add new configs after I ship a new site. I have quite some apps serving with Nginx actually:

http://repo.respo.site/
http://repo.tiye.me/

**Comment by Deraen** [comment]
I don't know how I can help you with this. Your setup is so different to everything I have used that I don't know what could cause problems.

Asset-paths itself should not affect boot-reload at all. As an example of this you can take look at Saapas example which doesn't set asset-path: https://github.com/Deraen/saapas/blob/master/build.boot

**Comment by jiyinyiyong** [comment]
Hope that I can find more clues in the future.

**Comment by jiyinyiyong** [comment]
I got a guess when I see this piece of code https://github.com/boot-clj/boot/blob/ac835cea8c18e926bb843e01579b86e3f30458d2/boot/core/src/boot/core.clj#L738

In the function `watch-dirs` it checked if there files in the `dirs`, it not, the watcher will not be started. The special thing in my project is all the source files are imported with `start-stack-editor!` task, and put files into `resource-paths` internally. So if no file is detected in `assets` too, it will be regarded as no files.

Not sure, but it can be reasonable for my case.

**Comment by Deraen** [comment]
I think there is nothing to fix in Boot-reload here.
